import { applyServiceFeeToOrder, buildConferenceEscPos, buildConferenceHtml, mergeOrdersForConference } from '../src/utils/conferencePrint';
let ok = 0, bad = 0;
const t = (n: string, c: boolean, x = '') => { c ? ok++ : bad++; console.log(`${c ? 'PASS' : 'FAIL'}  ${n}${c ? '' : '  -> ' + x}`); };
const mesa: any = { id: 'o1', shortCode: 'TK-1', orderType: 'mesa', tableNumber: 1, restaurantSlug: 'japones', items: [{ name: 'Guioza', quantity: 1, unitPrice: 28, totalPrice: 28 }], subtotal: 28, discount: 0, deliveryFee: 0, total: 28 };
const a = applyServiceFeeToOrder(mesa, undefined, true);
t('mesa aberta imprime com 10% por padrão', a.serviceFee === 2.8 && a.total === 30.8, JSON.stringify([a.serviceFee, a.total]));
const b = applyServiceFeeToOrder(mesa, false, true);
t('botão desativado: sai sem 10%', b.serviceFee === 0 && b.total === 28);
const c = applyServiceFeeToOrder(mesa, true, false);
t('botão ativo força 10% mesmo com padrão desligado', c.serviceFee === 2.8);
const d = applyServiceFeeToOrder(mesa, undefined, false);
t('padrão do sistema desligado: sem 10%', d.serviceFee === 0);
const paid = { ...mesa, serviceFee: 2.8, total: 30.8 };
t('conta já paga mantém o valor gravado', applyServiceFeeToOrder(paid, undefined, true).total === 30.8);
const deliv: any = { ...mesa, orderType: 'delivery', deliveryFee: 7, total: 35 };
t('delivery nunca recebe taxa de serviço', applyServiceFeeToOrder(deliv, true, true).serviceFee === undefined);
const m2 = mergeOrdersForConference([mesa, { ...mesa, id: 'o2', subtotal: 12, total: 12 }]);
const m2f = applyServiceFeeToOrder(m2, undefined, true);
t('várias comandas: 10% sobre o total da mesa', m2f.subtotal === 40 && m2f.serviceFee === 4 && m2f.total === 44, JSON.stringify([m2f.subtotal, m2f.serviceFee, m2f.total]));
const esc = buildConferenceEscPos(a, { name: 'Tokio' } as any, '80mm', { kind: 'comum', paymentMethod: 'pix' });
t('ESC/POS comum: título, 10% e pagamento', /CUPOM COMUM - NAO FISCAL/.test(esc) && /Taxa servico 10%/.test(esc) && /30,80/.test(esc) && /PIX/.test(esc));
const fis = buildConferenceHtml(a, { name: 'Tokio' } as any, '80mm', { kind: 'fiscal', paymentMethod: 'credito' });
t('HTML fiscal: título de Nota Fiscal e 10%', /NOTA FISCAL \(NFC-e\)/.test(fis) && /Taxa de servico \(10%\)/.test(fis) && /CREDITO/.test(fis));
const conf = buildConferenceEscPos(a, { name: 'Tokio' } as any, '80mm');
t('conferência continua "NAO FISCAL"', /CONFERENCIA - NAO FISCAL/.test(conf));
console.log(`\n${ok} ok, ${bad} falhas`);
process.exit(bad ? 1 : 0);
