import { crc16, buildPixBrCode, cityFromAddress } from '../src/utils/pix';
import { waNumber, waLink, socialHandle, orderChannels } from '../src/utils/contactLinks';
import { hasDemoData, sanitizeDemoRestaurant, missingRealData } from '../src/utils/demoData';
import { INITIAL_RESTAURANTS } from '../src/data/seedData';
let ok = 0, bad = 0;
const t = (n: string, c: boolean, x = '') => { c ? ok++ : bad++; console.log(`${c ? 'PASS' : 'FAIL'}  ${n}${c ? '' : ' -> ' + x}`); };
t('CRC16-CCITT vetor padrão "123456789" = 29B1', crc16('123456789') === '29B1', crc16('123456789'));
// Exemplo do manual do BCB (chave +5561..., sem valor)
const code = buildPixBrCode({ key: 'teste@exemplo.com', name: "Forno D'Oro Pizzeria", city: 'Rio das Ostras', amount: 89.9 });
t('PIX começa com 000201 e termina com CRC válido', code.startsWith('000201') && code.slice(-4) === crc16(code.slice(0, -4)), code);
t('PIX contém valor 89.90 e BR.GOV.BCB.PIX', code.includes('540589.90') && code.includes('br.gov.bcb.pix'));
t('nome sem acento/apóstrofo e ≤25', /5919FORNO DORO PIZZERIA/.test(code), code);
t('cidade ≤15 sem acento', code.includes('6014RIO DAS OSTRAS'), code);
t('PIX sem chave lança erro', (() => { try { buildPixBrCode({ key: ' ', name: 'x' }); return false; } catch { return true; } })());
t('cidade extraída do endereço', cityFromAddress('Rua A, 10 - Centro, Rio das Ostras - RJ') === 'Rio das Ostras');
t('wa: 11 dígitos ganha 55', waNumber('(22) 99876-5432') === '5522998765432');
t('wa: número curto/inválido = null', waNumber('1234') === null && waNumber('') === null && waLink('abc') === null);
t('wa: link com texto codificado', waLink('22998765432', 'Olá & pedido')!.includes('text=Ol%C3%A1%20%26%20pedido'));
t('handle aceita @, url e usuário', socialHandle('@sakura.sushi') === 'sakura.sushi' && socialHandle('https://instagram.com/sakura.sushi/') === 'sakura.sushi' && socialHandle('a b') === null);
t('7 restaurantes oficiais no seed', Object.keys(INITIAL_RESTAURANTS).length === 7);
const names = Object.values(INITIAL_RESTAURANTS).map((r: any) => r.name);
t('nomes oficiais exatos', JSON.stringify(names) === JSON.stringify(['Sakura Sushi House','Cantina Bella Vista',"Forno D'Oro Pizzeria",'Burger Craft & Beer','Il Nobile Risotteria & Tartufi','Fuego & Brasa Steakhouse','Botanique Gastronomia Vegetal']), JSON.stringify(names));
t('seed sem dados de demonstração', Object.values(INITIAL_RESTAURANTS).every((r: any) => hasDemoData(r).length === 0));
t('seed sem avaliações/notas inventadas', Object.values(INITIAL_RESTAURANTS).every((r: any) => r.reviewCount === 0 && r.rating === 0 && !(r.reviewsInfo?.items || []).length));
t('seed: contatos vazios (pendentes p/ o dono)', Object.values(INITIAL_RESTAURANTS).every((r: any) => missingRealData(r).length === 4));
const legacy: any = { slug: 'vegano', name: 'Botanique Gastronomia Vegetal Prime', whatsapp: '5511974569911', phone: '(22) 2760-0000', pixKey: 'botanique@tokioinbox.com.br', reviewsInfo: { items: [{ author: 'Renan Castilho' }] }, rating: 4.9, reviewCount: 362 };
const m = sanitizeDemoRestaurant(legacy);
t('migração: renomeia Prime', m.value.name === 'Botanique Gastronomia Vegetal');
t('migração: limpa WhatsApp/PIX/avaliações de exemplo', m.value.whatsapp === '' && m.value.pixKey === '' && m.value.reviewCount === 0);
t('migração: PRESERVA telefone real já cadastrado', m.value.phone === '(22) 2760-0000');
t('migração é idempotente', sanitizeDemoRestaurant(m.value).changed === false);
t('canais: sem dados → nenhum botão', orderChannels({ whatsapp: '', instagram: '' } as any, 'x').length === 0);
const ch = orderChannels({ whatsapp: '22998765432', instagram: '@loja', facebook: 'lojapage' } as any, 'Oi');
t('canais: WhatsApp+Instagram+Facebook', ch.map((c) => c.id).join() === 'whatsapp,instagram,facebook');
t('canais: dono pode desligar um', orderChannels({ whatsapp: '22998765432', instagram: '@loja', orderButtons: { instagram: false } } as any, 'Oi').map((c) => c.id).join() === 'whatsapp');
console.log(`\n${ok} ok, ${bad} falhas`); process.exit(bad ? 1 : 0);
